#!/usr/bin/env bash
# Generates MacApp/Sources/Generated/BuildInfo.swift from the VERSION file + git,
# so every build is self-identifying (semver + monotonic build number + commit).
# Run before `swift build` (scripts/build.sh does this) and in CI.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=$(tr -d '[:space:]' < VERSION 2>/dev/null || echo "0.0.0")
BUILD=$(git rev-list --count HEAD 2>/dev/null || echo "0")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "nogit")
DATE=$(date +%Y-%m-%d)
DIRTY=""
if ! git diff --quiet --ignore-submodules HEAD 2>/dev/null; then DIRTY="+"; fi

OUT="MacApp/Sources/Core/Generated/BuildInfo.swift"
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
// Generated by scripts/stamp-version.sh — do not edit by hand.
// Build identity baked in at compile time so every build is traceable.
public enum BuildInfo {
    public static let version = "$VERSION"          // semantic version (from /VERSION)
    public static let build   = "$BUILD"            // git commit count (monotonic)
    public static let commit  = "$COMMIT$DIRTY"     // short SHA (+ = uncommitted changes)
    public static let date    = "$DATE"             // build date

    /// e.g. "1.1.0 (build 214 · a1b2c3d)"
    public static var display: String { "\(version) (build \(build) · \(commit))" }
}
EOF
echo "Stamped $OUT — v$VERSION build $BUILD $COMMIT$DIRTY"
